
apiVersion: v1
kind: Pod
metadata:
  name: limits-pod
spec:
  containers:
  - name: apache-container
    image: httpd:latest

    resources:
      requests:
        memory: "128Mi"
        cpu:    "500m"  #mili cores/cpus or half a core
      limits:
        memory: "256Mi"
        cpu:    "1000m"  #mili cores/cpus or one core