apiVersion: v1
Kind: Service
metadata:
  name: frontend-service
  labels:
    type: service
spec:
  type: ClusterIP
  selector:
    type: web-app
  ports:
    - name: http
      port: 80 #Port exposed by the service
      targetPort: 80 #Port on the pod that the service will forward traffic to