apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  labels:
    type: web-app
spec:
  containers:
    - name: web-server-apache
      image: httpd:latest
      ports:
        - containerPort: 80 #Also de target port
    - name: web-server-tomcat
      image: tomcat:latest
      ports:
        - containerPort: 8080