apiVersion: v1
kind: Pod

metadata:
  name: pod1
  labels:
    app: myapp
    tier: frontend

spec:
  containers:
  - name: redis-container
    image: redis:latest
    ports:
    - containerPort: 6379
    volumeMounts:
    - name: cache-storage
      mountPath: /data

volumes:
  - name: cache-storage
    emptyDir: {}